[project]
name = "asmr"
version = "0.1.0"
description = "A Small Modern Robotics Lib"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "mujoco>=3.3.7",
    "numpy>=2.3.5",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["asmr*", "utils*"]